const express = require('express')
const cors = require('cors')
const bodyParser = require('body-parser')
const funcoesRoutes = require('./routes/funcoesRoutes')
const funcionariosRoutes = require('./routes/funcionariosRoutes')
const estadosRoutes = require('./routes/estadosRoutes')
const cidadesRoutes = require('./routes/cidadesRoutes')
const enderecosRoutes = require('./routes/enderecosRoutes')
const alunosRoutes = require('./routes/alunosRoutes')
const horariosRoutes = require('./routes/horariosRoutes')
const salasRoutes = require('./routes/salasRoutes')
const statusRoutes = require('./routes/statusRoutes')
const consultasRoutes = require('./routes/consultasRoutes')
const diaDaSemanaRoutes = require('./routes/diaDaSemanaRoutes')
const horariosFuncionariosRoutes = require('./routes/horariosFuncionariosRoutes')

const app = express()
const PORT = 3000

app.use(cors())
app.use(bodyParser.json())

app.use('/funcoes', funcoesRoutes)
app.use('/funcionarios', funcionariosRoutes)
app.use('/estados', estadosRoutes)
app.use('/cidades', cidadesRoutes)
app.use('/enderecos', enderecosRoutes)
app.use('/alunos', alunosRoutes)
app.use('/horarios', horariosRoutes)
app.use('/salas', salasRoutes)
app.use('/status', statusRoutes)
app.use('/consultas', consultasRoutes)
app.use('/dia-da-semana', diaDaSemanaRoutes)
app.use('/horarios-funcionarios', horariosFuncionariosRoutes)

app.listen(PORT, () => {
    console.log(`Servidor rodando na porta ${PORT}`)
})
